# Modeled after https://salsa.debian.org/freedombox-team/android-app/blob/master/.gitlab-ci.yml
# # https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS: "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - test
  - build
  - checkIcons
  - pages

tests:
  stage: test
  script:
    - ./gradlew test

assemble:
  stage: build
  script:
    - ./gradlew assembleChromaticDebug
    - ./gradlew assembleChromaticRelease
    - ./gradlew assembleMonochromaticDebug
    - ./gradlew assembleMonochromaticRelease
  artifacts:
    paths:
      - app/build/outputs/

icons:
  stage: checkIcons
  script:
    - bash check_icons.sh

pages:
  stage: deploy
  script:
    - bash process5_website_xml.sh
    - mv website public
  artifacts:
    paths:
      - public
  only:
    - master
